// <auto-generated />
using System;
using AiResearchers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiResearchers.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522111944_AddInterviewAnswerRound")]
    partial class AddInterviewAnswerRound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiResearchers.Core.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OutlineSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OutlineSectionId");

                    b.HasIndex("ResearchTaskId");

                    b.HasIndex("SourceId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.FocusArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTaskId");

                    b.ToTable("FocusAreas");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTaskId");

                    b.ToTable("InterviewAnswers");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.OutlineSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTaskId");

                    b.ToTable("OutlineSections");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.ProgressEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTaskId");

                    b.ToTable("ProgressEvents");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTaskId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.ResearchTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<string>("Depth")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ResearchTasks");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FocusAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FocusAreaId");

                    b.HasIndex("ResearchTaskId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Finding", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.OutlineSection", "OutlineSection")
                        .WithMany("Findings")
                        .HasForeignKey("OutlineSectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("Findings")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiResearchers.Core.Entities.Source", "Source")
                        .WithMany("Findings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutlineSection");

                    b.Navigation("ResearchTask");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.FocusArea", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("FocusAreas")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.InterviewAnswer", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("InterviewAnswers")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.OutlineSection", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("OutlineSections")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.ProgressEvent", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("ProgressEvents")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Report", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithOne("Report")
                        .HasForeignKey("AiResearchers.Core.Entities.Report", "ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Source", b =>
                {
                    b.HasOne("AiResearchers.Core.Entities.FocusArea", "FocusArea")
                        .WithMany("Sources")
                        .HasForeignKey("FocusAreaId");

                    b.HasOne("AiResearchers.Core.Entities.ResearchTask", "ResearchTask")
                        .WithMany("Sources")
                        .HasForeignKey("ResearchTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FocusArea");

                    b.Navigation("ResearchTask");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.FocusArea", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.OutlineSection", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.ResearchTask", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("FocusAreas");

                    b.Navigation("InterviewAnswers");

                    b.Navigation("OutlineSections");

                    b.Navigation("ProgressEvents");

                    b.Navigation("Report");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AiResearchers.Core.Entities.Source", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
